name: scalpsense # Replace 'scalpsense' with your project's name
publish_to: 'scalpsense' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  url_launcher: ^6.3.1
  image_picker: ^1.1.2
  dots_indicator: ^3.0.0
  curved_navigation_bar: ^1.0.6
  shared_preferences: ^2.3.3
  http: ^1.2.2
#  modal_progress_hud_nsn: ^0.5.1
#  awesome_dialog: ^3.2.1
#  firebase_auth: ^5.3.4
#  firebase_core: ^3.9.0
#  cloud_firestore: ^5.6.0
#  validators: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/front-end/assets/images/revive_hair.png
    - lib/front-end/assets/icons/app_logo.png
    - lib/front-end/assets/images/scanner.png
    - lib/front-end/assets/images/blue background.jpg
    - lib/front-end/assets/images/carousel_item1.png
    - lib/front-end/assets/images/carousel_item2.png
    - lib/front-end/assets/images/carousel_item3.png
    - lib/front-end/assets/images/skin_type_4.png
    - lib/front-end/assets/images/hair_loss_types.png

  fonts:
    - family: Pacifico
      fonts:
        - asset: fonts/Pacifico-Regular.ttf
    - family: sans-serif
      fonts:
        - asset: lib/front-end/assets/fonts/SourceSans3-VariableFont_wght.ttf
    - family: CCZoinks
      fonts:
        - asset: lib/front-end/assets/fonts/CCZoinks.ttf
